//go:build !solution

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: meshpb/protocol.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerMeta is arbitrary message that is propagated with peer gossip.
type PeerMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMeta) Reset() {
	*x = PeerMeta{}
	mi := &file_meshpb_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMeta) ProtoMessage() {}

func (x *PeerMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMeta.ProtoReflect.Descriptor instead.
func (*PeerMeta) Descriptor() ([]byte, []int) {
	return file_meshpb_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmptyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyData) Reset() {
	*x = EmptyData{}
	mi := &file_meshpb_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyData) ProtoMessage() {}

func (x *EmptyData) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyData.ProtoReflect.Descriptor instead.
func (*EmptyData) Descriptor() ([]byte, []int) {
	return file_meshpb_protocol_proto_rawDescGZIP(), []int{1}
}

type NewPeerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerEndpoint  string                 `protobuf:"bytes,1,opt,name=peer_endpoint,json=peerEndpoint,proto3" json:"peer_endpoint,omitempty"`
	PeerMeta      *PeerMeta              `protobuf:"bytes,2,opt,name=peer_meta,json=peerMeta,proto3" json:"peer_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPeerData) Reset() {
	*x = NewPeerData{}
	mi := &file_meshpb_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPeerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPeerData) ProtoMessage() {}

func (x *NewPeerData) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPeerData.ProtoReflect.Descriptor instead.
func (*NewPeerData) Descriptor() ([]byte, []int) {
	return file_meshpb_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *NewPeerData) GetPeerEndpoint() string {
	if x != nil {
		return x.PeerEndpoint
	}
	return ""
}

func (x *NewPeerData) GetPeerMeta() *PeerMeta {
	if x != nil {
		return x.PeerMeta
	}
	return nil
}

var File_meshpb_protocol_proto protoreflect.FileDescriptor

const file_meshpb_protocol_proto_rawDesc = "" +
	"\n" +
	"\x15meshpb/protocol.proto\"\x1e\n" +
	"\bPeerMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\v\n" +
	"\tEmptyData\"Z\n" +
	"\vNewPeerData\x12#\n" +
	"\rpeer_endpoint\x18\x01 \x01(\tR\fpeerEndpoint\x12&\n" +
	"\tpeer_meta\x18\x02 \x01(\v2\t.PeerMetaR\bpeerMeta2S\n" +
	"\rGossipService\x12\x1e\n" +
	"\x04Ping\x12\n" +
	".EmptyData\x1a\n" +
	".EmptyData\x12\"\n" +
	"\x06Update\x12\f.NewPeerData\x1a\n" +
	".EmptyDataB'Z%gitlab.com/slon/shad-go/gossip/meshpbb\x06proto3"

var (
	file_meshpb_protocol_proto_rawDescOnce sync.Once
	file_meshpb_protocol_proto_rawDescData []byte
)

func file_meshpb_protocol_proto_rawDescGZIP() []byte {
	file_meshpb_protocol_proto_rawDescOnce.Do(func() {
		file_meshpb_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshpb_protocol_proto_rawDesc), len(file_meshpb_protocol_proto_rawDesc)))
	})
	return file_meshpb_protocol_proto_rawDescData
}

var file_meshpb_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meshpb_protocol_proto_goTypes = []any{
	(*PeerMeta)(nil),    // 0: PeerMeta
	(*EmptyData)(nil),   // 1: EmptyData
	(*NewPeerData)(nil), // 2: NewPeerData
}
var file_meshpb_protocol_proto_depIdxs = []int32{
	0, // 0: NewPeerData.peer_meta:type_name -> PeerMeta
	1, // 1: GossipService.Ping:input_type -> EmptyData
	2, // 2: GossipService.Update:input_type -> NewPeerData
	1, // 3: GossipService.Ping:output_type -> EmptyData
	1, // 4: GossipService.Update:output_type -> EmptyData
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meshpb_protocol_proto_init() }
func file_meshpb_protocol_proto_init() {
	if File_meshpb_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshpb_protocol_proto_rawDesc), len(file_meshpb_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshpb_protocol_proto_goTypes,
		DependencyIndexes: file_meshpb_protocol_proto_depIdxs,
		MessageInfos:      file_meshpb_protocol_proto_msgTypes,
	}.Build()
	File_meshpb_protocol_proto = out.File
	file_meshpb_protocol_proto_goTypes = nil
	file_meshpb_protocol_proto_depIdxs = nil
}
